import string

res = {}
ciphertext = """azwcwlugblyciuohxfoxaiallcsrrwhxobzzupubzxfuewbcxaxsxawbwpxfusbaxuzcxoxucokoabcxollubugaucpwhuakbobzzwgucxaexfoxaialljuohxhsupoaxfobzollukaobeuxwxfucoguxfoxaxoquxfacwjlakoxawbphuulyiaxfwsxobygubxolhucuhnoxawbwhrshrwcuwpunocawbobzxfoxaialliullobzpoaxfpsllyzacefohkuxfuzsxaucwpxfuwppaeuwbifaefaogojwsxxwubxuhcwfulrguk"""
#ciphertext = """kvqkqdgepdakywcjvzclkokdnkwhrgtlcffvgxgffljwegpkvavmvaqfqxvzgmpavwfkvsvwusiskfulcdnwpwoagkhgtwkypspvfgowulkuvzclkokdntgstltmgxcavzcffsndgykspuglqljwusowcffljsvayandqtgqvzggtvgjughljwrjgkkvgfvghljwwfklgvulclgkcffljwqjfwtkqxvzgghxkugjusrhqaplgvqngjowcuegtvkfilqjgywdclkgpkcffljwwfkxqjouqvgghekdkljcjabwkvaewugjwnhowigf"""
#ciphertext = """ujltkvbpxowvvcoqcubiubrkjofvtlpwvbuwplxtvkpytvkflnbzqxdcqgkqeqxuykbvlturvpxtwdmcepwwjvlunrpmvtqrsflocuzcqerobkqujduarvyrvngujlomqpvkjpjxcvxtroizjvkjvlohddvqpvkjpjjuzsqqhylujlukwjukjikmaxowvvcoujrviktvxealucqevkjpnbdrvvludxuarvuwjnoncboqwgkqecqzvkjpjpfgcwwjhbpwzptnbvlucejvbpwpjikuhlofrvvwsawpfrtqzjvkpwwbpbdqddjloi"""

for letter in ciphertext:
	res[letter] = res.get(letter, 0)+1

	
print("Count of letters is: \n" + str(res))

